In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output




In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))




In [4]:
print(q_table)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Initializing Q-Learning Parameters


In [38]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001



Coding The Q-Learning Algorithm Training Loop



In [39]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
           action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward 

        if done == True: 
            break
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

After All Episodes Complete



In [40]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000




********Average reward per thousand episodes********

1000 :  0.05500000000000004
2000 :  0.17100000000000012
3000 :  0.4110000000000003
4000 :  0.5130000000000003
5000 :  0.5880000000000004
6000 :  0.6120000000000004
7000 :  0.6760000000000005
8000 :  0.6850000000000005
9000 :  0.6650000000000005
10000 :  0.6390000000000005


In [10]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)






********Q-table********

[[0.51370456 0.48187453 0.4883082  0.492021  ]
 [0.23846247 0.25444812 0.31656009 0.49106897]
 [0.4237979  0.41391813 0.4100767  0.45537804]
 [0.36027577 0.33389811 0.2955056  0.44078573]
 [0.52736521 0.42187039 0.45900475 0.3482556 ]
 [0.         0.         0.         0.        ]
 [0.16489702 0.1634903  0.30601277 0.11801914]
 [0.         0.         0.         0.        ]
 [0.38601709 0.48964258 0.36592747 0.57169493]
 [0.35134433 0.65253862 0.43792537 0.41800307]
 [0.55661059 0.42180629 0.3496849  0.27898508]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.46592346 0.54798749 0.76604318 0.52782709]
 [0.7186347  0.93225331 0.70906513 0.75756649]
 [0.         0.         0.         0.        ]]
